"use client"

import { useQuery } from "@tanstack/react-query"
import { Activity, Bell, BookOpenText, CalendarDays, CircleDot, ExternalLink, LayoutDashboard, RefreshCw, Route, Server, Settings2, Waypoints } from "lucide-react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { useEffect, useState } from "react"
import { BackfillSheet } from "@/components/operations/backfill-sheet"
import { DataColumnHeaders } from "@/components/operations/data-column-headers"
import { DatabaseObservability } from "@/components/operations/database-observability"
import { HealthStrip } from "@/components/operations/health-strip"
import { OperatorActionDialog } from "@/components/operations/operator-action-dialog"
import { OperatorMenu } from "@/components/operations/operator-menu"
import { OperatorSignIn } from "@/components/operations/sign-in"
import { Sparkline } from "@/components/operations/sparkline"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarInset, SidebarNavButton, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { Skeleton } from "@/components/ui/skeleton"
import { Table, TableBody, TableCell, TableHeader, TableRow } from "@/components/ui/table"
import { Tooltip } from "@/components/ui/tooltip"
import { useOperationsAuth } from "@/lib/auth-context"
import { operationsEnvironment } from "@/lib/app-environment"
import { fetchOverview, OperationsForbiddenError } from "@/lib/operations-api"
import type { Backfill, EnvironmentName, Gap, Overview, Span } from "@/lib/operations-types"

const nav = [
  ["overview", "Overview", LayoutDashboard], ["ingestion", "Ingestion", Settings2], ["appview", "AppView", Server], ["gaps", "Gaps", Waypoints], ["backfills", "Backfills", RefreshCw], ["alerts", "Alerts", Bell], ["runbooks", "Runbooks", BookOpenText],
] as const
const collectionRows = [
  ["site.standard.document", 512, 78, 3, 593, 74, 220, 980, 0.01], ["site.standard.entry", 1264, 193, 6, 1463, 96, 310, 1210, 0.02], ["app.skyreader.feed.subscription", 852, 41, 1, 894, 62, 190, 760, 0], ["site.standard.graph.subscription", 274, 12, 0, 286, 28, 160, 540, 0],
] as const

type Runbook = { slug: string; title: string; body: string }

export function OperationsConsole({ section, runbooks }: { section: string[]; runbooks: Runbook[] }) {
  const router = useRouter()
  const auth = useOperationsAuth()
  const demo = process.env.NEXT_PUBLIC_OPERATIONS_DEMO_MODE === "1"
  const environment = operationsEnvironment()
  const [autoRefresh, setAutoRefresh] = useState(true)
  const [demoSessionActive, setDemoSessionActive] = useState(true)
  const [selectedGap, setSelectedGap] = useState<Gap>()
  const [drawerDismissed, setDrawerDismissed] = useState(false)
  const current = section[0] || "overview"
  const overview = useQuery({ queryKey: ["operations-overview", environment], queryFn: () => fetchOverview(auth.session), enabled: demo || Boolean(auth.session), refetchInterval: autoRefresh ? 15_000 : false, placeholderData: (previous) => previous })
  useEffect(() => { if (overview.error instanceof OperationsForbiddenError) auth.setForbidden(true) }, [overview.error, auth])
  if (auth.loading) return <LoadingScreen />
  if (!auth.session && (!demo || !demoSessionActive)) return <OperatorSignIn />
  const data = overview.data
  const effectiveSelectedGap = selectedGap ?? (demo && !drawerDismissed ? data?.gaps[0] : undefined)
  return <SidebarProvider><Sidebar><SidebarHeader><div className="flex min-w-0 items-center gap-2"><span className="grid size-7 shrink-0 place-items-center text-primary"><Activity className="size-5" /></span><div className="min-w-0"><p className="truncate text-xs font-semibold">The Social Wire</p><p className="ops-label">Operations</p></div></div></SidebarHeader><SidebarContent><nav aria-label="Operations"><div className="grid gap-1">{nav.map(([key, label, Icon]) => <SidebarNavButton key={key} active={current === key} icon={<Icon className="size-3.5" />} onClick={() => router.push(key === "overview" ? "/" : `/${key}`)}>{label}</SidebarNavButton>)}</div></nav></SidebarContent><SidebarFooter><SidebarTrigger /></SidebarFooter></Sidebar><SidebarInset><TopBar environment={environment} autoRefresh={autoRefresh} setAutoRefresh={setAutoRefresh} refreshedAt={data?.refreshedAt} onRefresh={() => overview.refetch()} operator={auth.session?.did ?? "did:plc:demo-operator"} onSignOut={async () => { await auth.signOut(); if (demo) setDemoSessionActive(false) }} /><MobileNav current={current} /><div className="p-3 sm:p-4"><PageHeading current={current} />{overview.isLoading || !data ? <OverviewSkeleton /> : <RouteContent current={current} traceId={section[1]} data={data} environment={environment} runbooks={runbooks} onSelectGap={(gap) => { setSelectedGap(gap); setDrawerDismissed(false) }} />}{overview.error && !(overview.error instanceof OperationsForbiddenError) ? <p role="alert" className="mt-3 text-xs text-destructive">{overview.error.message}</p> : null}</div></SidebarInset><BackfillSheet key={`${environment}-${effectiveSelectedGap?.id ?? "none"}`} gap={effectiveSelectedGap} environment={environment} open={Boolean(effectiveSelectedGap)} onOpenChange={(open) => { if (!open) { setSelectedGap(undefined); setDrawerDismissed(true) } }} /></SidebarProvider>
}

function TopBar({ environment, autoRefresh, setAutoRefresh, refreshedAt, onRefresh, operator, onSignOut }: { environment: EnvironmentName; autoRefresh: boolean; setAutoRefresh: (value: boolean) => void; refreshedAt?: string; onRefresh: () => void; operator: string; onSignOut: () => Promise<void> }) {
  return <header className="sticky top-0 z-30 flex min-h-12 flex-wrap items-center gap-x-4 gap-y-2 border-b bg-background/95 px-3 py-2 backdrop-blur sm:px-4"><div className="flex items-center gap-2"><span className="ops-label normal-case tracking-normal">Environment</span><Badge tone={environment === "production" ? "danger" : "warning"}>{environment === "production" ? "Production" : "Development"}</Badge></div><div className="hidden h-7 border-l sm:block" /><div className="flex items-center gap-2 text-xs"><span>System State</span><Badge tone="success"><CircleDot className="mr-1 size-2.5" /> Healthy</Badge></div><div className="ml-auto flex items-center gap-3"><div className="hidden items-center gap-2 lg:flex"><span className="ops-label normal-case tracking-normal">Time Range</span><Button variant="outline"><span>Last 15 minutes</span><CalendarDays /></Button></div><label className="flex items-center gap-1.5 text-[10px]"><span>Auto-refresh</span><button type="button" role="switch" aria-checked={autoRefresh} onClick={() => setAutoRefresh(!autoRefresh)} className={`relative h-4 w-7 rounded-full border ${autoRefresh ? "bg-primary" : "bg-muted"}`}><span className={`absolute top-0.5 size-2.5 rounded-full bg-white transition-[left] ${autoRefresh ? "left-3.5" : "left-0.5"}`} /></button></label><div className="hidden text-right text-[9px] text-muted-foreground xl:block"><p>Last refreshed</p><p>{refreshedAt ? new Date(refreshedAt).toLocaleString() : "—"}</p></div><Tooltip label="Refresh Now"><Button variant="ghost" size="icon" onClick={onRefresh}><RefreshCw /></Button></Tooltip><OperatorMenu operator={operator} onSignOut={onSignOut} /></div></header>
}

function MobileNav({ current }: { current: string }) { return <nav aria-label="Mobile Operations" className="flex overflow-x-auto border-b p-2 md:hidden">{nav.map(([key, label]) => <Link key={key} href={key === "overview" ? "/" : `/${key}`} className={`rounded-md px-3 py-1.5 text-[11px] ${current === key ? "bg-accent text-accent-foreground" : "text-muted-foreground"}`}>{label}</Link>)}</nav> }
function PageHeading({ current }: { current: string }) { const label = nav.find(([key]) => key === current)?.[1] ?? (current === "traces" ? "Trace Detail" : "Overview"); return <div className="mb-3 flex items-center gap-3"><h1 className="text-lg font-semibold tracking-tight">{label}</h1>{current === "overview" ? <Button variant="link" size="sm"><Route /> Open in Trace / Metrics Explorer <ExternalLink /></Button> : null}</div> }

function RouteContent({ current, traceId, data, environment, runbooks, onSelectGap }: { current: string; traceId?: string; data: Overview; environment: EnvironmentName; runbooks: Runbook[]; onSelectGap: (gap: Gap) => void }) {
  if (current === "ingestion") return <div className="grid gap-3"><LiveStream data={data} /><CollectionTable /><GapsTable gaps={data.gaps} onSelect={onSelectGap} /></div>
  if (current === "appview") return <div className="grid gap-3"><RequestTable spans={data.recentTraces} /><DatabaseObservability overview={data} /><ServiceTable data={data} /></div>
  if (current === "gaps") return <GapsTable gaps={data.gaps} onSelect={onSelectGap} expanded />
  if (current === "backfills") return <BackfillsTable backfills={data.backfills} environment={environment} expanded />
  if (current === "alerts") return <AlertsTable data={data} environment={environment} />
  if (current === "runbooks") return <Runbooks runbooks={runbooks} />
  if (current === "traces") return <TraceDetail span={data.recentTraces.find((span) => span.traceId === traceId) ?? data.recentTraces[0]} />
  return <div className="grid gap-3"><HealthStrip overview={data} /><LiveStream data={data} /><CollectionTable /><RequestTable spans={data.recentTraces} /><DatabaseObservability overview={data} /><CollectionHealth /><div className="flex w-full flex-col gap-3"><GapsTable gaps={data.gaps} onSelect={onSelectGap} /><BackfillsTable backfills={data.backfills} environment={environment} /></div></div>
}

function Section({ title, action, children }: { title: React.ReactNode; action?: React.ReactNode; children: React.ReactNode }) { return <section className="ops-panel min-w-0 overflow-hidden"><header className="flex min-h-9 items-center justify-between border-b px-3"><h2 className="text-xs font-semibold">{title}</h2>{action}</header>{children}</section> }
function LiveStream({ data }: { data: Overview }) { const state = data.ingestion; const delta = (state?.lastReceivedCursor ?? 0) - (state?.lastCommittedCursor ?? 0); const metrics = [["Jetstream Instance", "dev-js-03"], ["Connection Duration", "2d 14h 32m 11s"], ["Replay Cursor", String((state?.lastCommittedCursor ?? 0) - 5_000_000)], ["Last Received (μs)", String(state?.lastReceivedCursor ?? "—")], ["Last Committed (μs)", String(state?.lastCommittedCursor ?? "—")], ["Cursor Delta", `${delta.toLocaleString()} μs`], ["R→C p50 / p95", "410 ms / 1.82 s"], ["In-Flight", String(state?.queueDepth ?? 0)], ["Reconnect Reason", state?.lastDisconnectReason ?? "—"]]; return <Section title={<span className="flex items-center gap-2">Live Stream / Consumers <Badge tone="success">● Connected</Badge></span>}><div className="grid grid-cols-2 divide-x divide-y sm:grid-cols-3 xl:grid-cols-9 xl:divide-y-0">{metrics.map(([label, value]) => <div key={label} className="min-w-0 p-3"><p className="text-[9px] text-muted-foreground">{label}</p><p className="mt-1 truncate font-mono text-[10px]">{value}</p></div>)}</div></Section> }
function CollectionTable() { return <Section title="Events / sec by Bounded Collection / Operation (top)"><Table><TableHeader><TableRow><DataColumnHeaders labels={["Collection", "Create (eps)", "Update (eps)", "Delete (eps)", "All Ops (eps)", "In-Flight", "p50 (ms) R→C", "p95 (ms) R→C", "Errors (eps)"]} /></TableRow></TableHeader><TableBody>{collectionRows.map((row) => <TableRow key={row[0]}>{row.map((cell, index) => <TableCell key={index} className={index === 0 ? "font-mono" : "font-mono tabular-nums"}>{cell}{index > 0 && index < 5 ? <Sparkline /> : null}</TableCell>)}</TableRow>)}</TableBody></Table></Section> }
function RequestTable({ spans }: { spans: Span[] }) { return <Section title={<span>AppView Request <span className="ml-2 text-[9px] font-normal text-muted-foreground">Showing recent correlated requests (last 15m)</span></span>} action={<Link href="/appview" className="text-[10px] text-primary">View all requests <ExternalLink className="inline size-3" /></Link>}><Table><TableHeader><TableRow><DataColumnHeaders labels={["Time", "Request ID", "Trace ID", "Route", "Status", "Total Latency", "Auth", "Cache", "DB Time", "Rows", "Resp Freshness", "View Trace"]} /></TableRow></TableHeader><TableBody>{spans.slice(0, 5).map((span) => <TableRow key={span.id}><TableCell className="font-mono">{new Date(span.startedAt).toLocaleTimeString()}</TableCell><TableCell className="font-mono">{span.id}</TableCell><TableCell className="font-mono">{span.traceId.slice(0, 16)}</TableCell><TableCell className="max-w-64 truncate font-mono">{span.attributes.route ?? span.name}</TableCell><TableCell><span className={span.status === "error" ? "text-destructive" : "ops-success"}>{span.status === "error" ? "500" : span.status}</span></TableCell><TableCell className="font-mono">{span.durationMs.toLocaleString()} ms</TableCell><TableCell>JWT</TableCell><TableCell>{span.attributes.cache_outcome?.toUpperCase() ?? "MISS"}</TableCell><TableCell className="font-mono">{Math.round(span.durationMs * 0.12)} ms</TableCell><TableCell>{span.name.includes("entries") ? 50 : 4}</TableCell><TableCell>&lt; 1s</TableCell><TableCell><Link href={`/traces/${span.traceId}`} className="text-primary">View Trace <ExternalLink className="inline size-3" /></Link></TableCell></TableRow>)}</TableBody></Table></Section> }
function CollectionHealth() { return <Section title="Collection Health (per bounded collection)"><Table><TableHeader><TableRow><DataColumnHeaders labels={["Collection", "Accepted (eps)", "Filtered (eps)", "Failed (eps)", "p95 Commit Time (ms)", "Newest-Event Age", "Lag (s)", "Status"]} /></TableRow></TableHeader><TableBody>{collectionRows.map((row, index) => <TableRow key={row[0]}><TableCell className="font-mono">{row[0]}</TableCell><TableCell>{row[4].toLocaleString()} <Sparkline /></TableCell><TableCell>{12 + index * 8} <Sparkline /></TableCell><TableCell>{row[8]} <Sparkline tone={index < 2 ? "warning" : "primary"} /></TableCell><TableCell>{row[7].toLocaleString()}</TableCell><TableCell>{(2.1 - index * 0.5).toFixed(1)}s</TableCell><TableCell>{(2.1 - index * 0.5).toFixed(1)}</TableCell><TableCell><span className={index < 2 ? "ops-warning" : "ops-success"}>{index < 2 ? "At Risk" : "Good"}</span></TableCell></TableRow>)}</TableBody></Table></Section> }
function GapsTable({ gaps, onSelect, expanded }: { gaps: Gap[]; onSelect: (gap: Gap) => void; expanded?: boolean }) { return <Section title={`Known Gaps (${gaps.length})`} action={!expanded ? <Link href="/gaps" className="text-[10px] text-primary">View all gaps <ExternalLink className="inline size-3" /></Link> : undefined}><Table><TableHeader><TableRow><DataColumnHeaders labels={["Status", "Cursor / Time Range (μs)", "Reason", "Detected", "Affected Collections", "Action"]} /></TableRow></TableHeader><TableBody>{gaps.map((gap) => <TableRow key={gap.id}><TableCell><Badge tone={gap.status === "confirmed" ? "danger" : gap.status === "backfilling" ? "warning" : "neutral"}>{gap.status}</Badge></TableCell><TableCell className="font-mono">{gap.startCursor ?? "—"} ..<br />{gap.endCursor ?? "—"}</TableCell><TableCell>{gap.reason.replaceAll("_", " ")}</TableCell><TableCell>{new Date(gap.detectedAt).toLocaleString()}</TableCell><TableCell>{gap.collections.length}</TableCell><TableCell><Button size="sm" variant="outline" onClick={() => onSelect(gap)}>Backfill</Button></TableCell></TableRow>)}</TableBody></Table></Section> }
function BackfillsTable({ backfills, environment, expanded }: { backfills: Backfill[]; environment: EnvironmentName; expanded?: boolean }) { return <Section title={`Active Backfills (${backfills.length})`} action={!expanded ? <Link href="/backfills" className="text-[10px] text-primary">View all backfills <ExternalLink className="inline size-3" /></Link> : undefined}><Table><TableHeader><TableRow><DataColumnHeaders labels={["Backfill ID", "Collection", "Range (μs)", "Progress", "Processed", "Rate", "Checkpoint (μs)", "Action"]} /></TableRow></TableHeader><TableBody>{backfills.map((job) => { const progress = job.estimatedCount ? Math.round(job.processedCount / job.estimatedCount * 100) : job.status === "completed" ? 100 : 0; const action = job.status === "running" ? "pause" : job.status === "paused" ? "resume" : undefined; return <TableRow key={job.id}><TableCell className="font-mono">{job.id}</TableCell><TableCell className="font-mono">{job.collections[0] ?? "PDS reconciliation"}</TableCell><TableCell className="font-mono">{job.startCursor ?? "—"} ..<br />{job.endCursor ?? "—"}</TableCell><TableCell><span className="font-mono">{progress}%</span><Progress value={progress} className="mt-1 w-20" /></TableCell><TableCell className="font-mono">{job.processedCount.toLocaleString()}</TableCell><TableCell>{job.status === "running" ? `${job.rateLimit} rps` : "—"}</TableCell><TableCell className="font-mono">{job.checkpointCursor ?? "—"}</TableCell><TableCell>{action ? <MutationActionButton environment={environment} path={`/v1/operations/backfills/${job.id}/${action}`} label={action === "pause" ? "Pause" : "Resume"} /> : <Badge>{job.status}</Badge>}</TableCell></TableRow> })}</TableBody></Table></Section> }
function AlertsTable({ data, environment }: { data: Overview; environment: EnvironmentName }) { return <Section title={`Operational Alerts (${data.alerts.length})`}><Table><TableHeader><TableRow><DataColumnHeaders labels={["Severity", "Status", "Rule", "Summary", "Opened", "Delivery", "Runbook", "Action"]} /></TableRow></TableHeader><TableBody>{data.alerts.map((alert) => { const action = alert.status === "open" ? "acknowledge" : alert.status === "acknowledged" ? "resolve" : undefined; return <TableRow key={alert.id}><TableCell><Badge tone={alert.severity === "critical" ? "danger" : "warning"}>{alert.severity}</Badge></TableCell><TableCell>{alert.status}</TableCell><TableCell className="font-mono">{alert.rule}</TableCell><TableCell>{alert.summary}</TableCell><TableCell>{new Date(alert.openedAt).toLocaleString()}</TableCell><TableCell>{alert.lastDeliveryError ? <span className="text-destructive">Failed</span> : `${alert.deliveryAttempts} attempt${alert.deliveryAttempts === 1 ? "" : "s"}`}</TableCell><TableCell><Link href={`/runbooks#${alert.runbookSlug}`} className="text-primary">Open Runbook</Link></TableCell><TableCell>{action ? <MutationActionButton environment={environment} path={`/v1/operations/alerts/${alert.id}/${action}`} label={action === "acknowledge" ? "Acknowledge" : "Resolve"} /> : <Badge tone="success">Resolved</Badge>}</TableCell></TableRow> })}</TableBody></Table></Section> }
const MutationActionButton = OperatorActionDialog
function ServiceTable({ data }: { data: Overview }) { return <Section title="Service State"><Table><TableHeader><TableRow><DataColumnHeaders labels={["Service", "Instance", "Liveness", "Readiness", "Freshness", "Completeness", "Version", "Heartbeat"]} /></TableRow></TableHeader><TableBody>{data.services.map((service) => <TableRow key={`${service.service}-${service.instanceId}`}><TableCell className="font-medium">{service.service}</TableCell><TableCell className="font-mono">{service.instanceId}</TableCell><TableCell>{service.liveness}</TableCell><TableCell>{service.readiness}</TableCell><TableCell>{service.freshness}</TableCell><TableCell>{service.completeness}</TableCell><TableCell className="font-mono">{service.version ?? "—"}</TableCell><TableCell>{new Date(service.heartbeatAt).toLocaleTimeString()}</TableCell></TableRow>)}</TableBody></Table></Section> }
function Runbooks({ runbooks }: { runbooks: Runbook[] }) { return <section className="ops-panel divide-y">{runbooks.map((runbook, index) => <article id={runbook.slug} key={runbook.slug} className="grid gap-3 p-4 sm:grid-cols-[32px_1fr]"><span className="grid size-7 place-items-center rounded-md bg-muted font-mono text-[10px]">{String(index + 1).padStart(2, "0")}</span><div><h2 className="text-xs font-semibold">{runbook.title}</h2><div className="mt-2 whitespace-pre-line text-[11px] leading-5 text-muted-foreground">{runbook.body}</div></div></article>)}</section> }
function TraceDetail({ span }: { span?: Span }) { if (!span) return <p className="text-xs text-muted-foreground">No trace found.</p>; return <div className="grid gap-3 lg:grid-cols-[1fr_320px]"><Section title={<span className="font-mono">Trace {span.traceId}</span>}><div className="p-4"><div className="relative ml-2 border-l pl-5">{["gateway.request", "gateway.appview.proxy", "appview.auth", "appview.cache.lookup", "appview.db.query", span.name].map((name, index) => <div key={`${name}-${index}`} className="relative mb-4 rounded-md border p-3 text-xs"><span className="absolute -left-[27px] top-3 size-3 rounded-full border-2 border-primary bg-background" /><div className="flex justify-between"><span className="font-mono">{name}</span><span className="font-mono text-muted-foreground">{Math.round(span.durationMs / (index + 1))} ms</span></div><Progress value={Math.max(8, 100 - index * 14)} className="mt-2" /></div>)}</div></div></Section><Section title="Span Attributes"><dl className="divide-y text-[11px]">{Object.entries(span.attributes).map(([key, value]) => <div key={key} className="grid grid-cols-2 gap-2 p-3"><dt className="font-mono text-muted-foreground">{key}</dt><dd className="break-all font-mono">{value}</dd></div>)}</dl></Section></div> }
function OverviewSkeleton() { return <div className="grid gap-3"><Skeleton className="h-24" /><Skeleton className="h-36" /><Skeleton className="h-52" /><Skeleton className="h-48" /></div> }
function LoadingScreen() { return <main className="grid min-h-svh place-items-center"><div className="text-center"><Activity className="mx-auto size-6 animate-pulse text-primary" /><p className="mt-2 text-xs text-muted-foreground">Restoring operator session…</p></div></main> }
